name: Build and push

on:
  push:
    branches:
      - "main"

env:
  REGISTRY: ghcr.io
  IMAGE_REPO: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    name: Build docker image and push to GCR
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }} .;
          docker image push ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}
